name: Deploy Full Stack App to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  backend-deploy:
    name: Deploy Backend to Elastic Beanstalk
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Create Deployment Zip
        run: zip -r ../server.zip . -x "node_modules/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: restaurant-booking
          environment_name: restaurant-env
          region: ${{ secrets.AWS_REGION }}
          version_label: v-${{ github.run_number }}
          deployment_package: ./server.zip

  frontend-deploy:
    name: Deploy Frontend to S3
    runs-on: ubuntu-latest
    needs: backend-deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync files to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --cache-control "max-age=0,no-cache,no-store,must-revalidate"
          bucket: cozy-bites-ayushi
          region: ${{ secrets.AWS_S3_REGION }}
        env:
          AWS_S3_BUCKET: cozy-bites-ayushi
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_S3_REGION }}
          SOURCE_DIR: web
